{% set name = "cuda-profiler-api" %}
{% set version = "13.3.27" %}
{% set cuda_version = "13.3" %}
{% set platform = "linux-x86_64" %}  # [linux64]
{% set platform = "linux-sbsa" %}  # [aarch64]
{% set platform = "windows-x86_64" %}  # [win]
{% set target_name = "x86_64-linux" %}  # [linux64]
{% set target_name = "sbsa-linux" %}  # [aarch64]
{% set target_name = "x64" %}  # [win]
{% set extension = "tar.xz" %}  # [not win]
{% set extension = "zip" %}  # [win]

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_profiler_api/{{ platform }}/cuda_profiler_api-{{ platform }}-{{ version }}-archive.{{ extension }}
  sha256: 5aa4df91651f19c2c7c3ac0531cdcd96e18f5227a60efb81b18ca282be719780  # [linux64]
  sha256: 527d1c76abe450d110af6404da6db18fd507b8e47af69cb2ed69348925b95fa8  # [aarch64]
  sha256: b41e9634dee36a7c31e121f636c43ba8b461de03de678bcb918060bd352fa2b8  # [win]

build:
  number: 0
  skip: true  # [osx]

requirements:
  build:
    - arm-variant * {{ arm_variant_type }}  # [aarch64]
    - cf-nvidia-tools 1  # [linux]
  host:
    - cuda-version {{ cuda_version }}
  run:
    - {{ pin_compatible("cuda-version", max_pin="x.x") }}
    - cuda-cudart-dev
  run_constrained:
    - arm-variant * {{ arm_variant_type }}  # [aarch64]

test:
  commands:
    - test -f $PREFIX/targets/{{ target_name }}/include/cuda_profiler_api.h  # [linux]
    - test -f $PREFIX/targets/{{ target_name }}/include/cudaProfiler.h       # [linux]
    - if not exist %LIBRARY_INC%\cuda_profiler_api.h exit 1  # [win]
    - if not exist %LIBRARY_INC%\cudaProfiler.h exit 1       # [win]

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license_file: LICENSE
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  license_family: Other
  summary: CUDA Profiler API Headers.
  description: |
    CUDA Profiler API Headers.
  doc_url: https://docs.nvidia.com/nsight-compute/ProfilingGuide/index.html#range-replay-define-range
  dev_url: https://docs.nvidia.com/nsight-compute/ProfilingGuide/index.html#range-replay-define-range

extra:
  recipe-maintainers:
    - conda-forge/cuda
