{% set name = "cuda-profiler-api" %}
{% set version = "13.2.86" %}
{% set cuda_version = "13.2" %}
{% set platform = "linux-x86_64" %}  # [linux64]
{% set platform = "linux-sbsa" %}  # [aarch64]
{% set platform = "windows-x86_64" %}  # [win]
{% set target_name = "x86_64-linux" %}  # [linux64]
{% set target_name = "sbsa-linux" %}  # [aarch64]
{% set target_name = "x64" %}  # [win]
{% set extension = "tar.xz" %}  # [not win]
{% set extension = "zip" %}  # [win]

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_profiler_api/{{ platform }}/cuda_profiler_api-{{ platform }}-{{ version }}-archive.{{ extension }}
  sha256: 6ca5a79ee76c03c807df8c6b4b484361de766ba08ce4216160bf2d41dcc5b8e1  # [linux64]
  sha256: 5275472e41e80a98200572bb553e69f5d0a7030e55c3c3fa3d524e38b0da5fb1  # [aarch64]
  sha256: c611ef0c8e8b81d8fd6cc5b728a5c6fc7e9491091273adc0aa9ff4356c2dcb7b  # [win]

build:
  number: 0
  skip: true  # [osx]

requirements:
  build:
    - arm-variant * {{ arm_variant_type }}  # [aarch64]
    - cf-nvidia-tools 1  # [linux]
  host:
    - cuda-version {{ cuda_version }}
  run:
    - {{ pin_compatible("cuda-version", max_pin="x.x") }}
    - cuda-cudart-dev
  run_constrained:
    - arm-variant * {{ arm_variant_type }}  # [aarch64]

test:
  commands:
    - test -f $PREFIX/targets/{{ target_name }}/include/cuda_profiler_api.h  # [linux]
    - test -f $PREFIX/targets/{{ target_name }}/include/cudaProfiler.h       # [linux]
    - if not exist %LIBRARY_INC%\cuda_profiler_api.h exit 1  # [win]
    - if not exist %LIBRARY_INC%\cudaProfiler.h exit 1       # [win]

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license_file: LICENSE
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  license_family: Other
  summary: CUDA Profiler API Headers.
  description: |
    CUDA Profiler API Headers.
  doc_url: https://docs.nvidia.com/nsight-compute/ProfilingGuide/index.html#range-replay-define-range
  dev_url: https://docs.nvidia.com/nsight-compute/ProfilingGuide/index.html#range-replay-define-range

extra:
  recipe-maintainers:
    - conda-forge/cuda
